### ISSUE TITLE
Support for obtaining ATR from SCardStatus

### ISSUE THREAD

**Issue by tarcieri** [bluetech/pcsc-rust#13]
I'm translating some C code which was invoking `SCardStatus` to get the ATR, and noticed it's presently listed as a TODO:

https://github.com/bluetech/pcsc-rust/blob/52f9e94/pcsc/src/lib.rs#L1075

Not a showstopper for me, but it'd be nice if it were supported.

**Comment by bluetech** [comment]
Yes, I'd like to add this. My plan is to add a `status2()` function which returns a struct with accessors for each of the return values, instead of a tuple like `status()` does.

Looking at it though, I noticed something I had missed before, that `SCardStatus()` in pcsclite and Windows are not compatible:

- pcsclite returns one reader name, Windows can return multiple (separated with `\0` and terminated with `\0\0`).

- pcsclite `pdwState` return value is a [bitmask](https://github.com/LudovicRousseau/PCSC/blob/20385efba2075d4c13acfea43d0abc8c38d8c106/src/PCSC/pcsclite.h.in#L257), while in Windows it's a simple [ordinal](https://github.com/amree/omnikey-mifare-samples-libraries/blob/8a4f8d3ea93a4afa1f2aca43a0957d9ac508e811/Include/winsmcrd.h#L212). In `pcsc` I made it a `bitflags`, which is incorrect on Windows. Not to mention that the values for Windows in `pcsc-sys` are actually wrong.

The first one is easy to handle, the second one less so, but I'll think of something.

**Comment by bluetech** [comment]
In the meantime, you can obtain the ATR like this:

https://github.com/bluetech/pcsc-rust/blob/65ce1af0fa2535251524a19bc8eb2dca347896e9/pcsc/examples/connect.rs#L39-L42

**Comment by tarcieri** [comment]
Oh awesome, thanks for the workaround!

**Comment by tarcieri** [comment]
@bluetech that seems to be working great and solves my immediate problem. Given that, feel free to close this issue.

**Comment by bluetech** [comment]
Fixed in c4cac64fb8fdaf53ed2c757ce49c3acd1a52c010. I punted on the `pdwState`, though I made sure it can be covered in a backward-compatible way. I'll release new versions of pcsc and pcsc-sys in a few days.

**Comment by tarcieri** [comment]
Awesome, thanks!

Should have a fun project built on `pcsc` soon: https://github.com/tarcieri/yubikey-piv.rs
