### ISSUE TITLE
Simulating card removal on Windows

### ISSUE THREAD

**Issue by CMMR2** [bluetech/pcsc-rust#14]
I have some Windows machines that are set up to allow logon via smartcard and automatically log the user out when the smartcard is removed from the reader. I'd like to be able to tell Windows that the card has been removed, even if it hasn't, so that it triggers Windows to log the user out. Is that possible do you think?

**Comment by bluetech** [comment]
Probably possible through the USB/device layer, but I don't know much about it on Windows.

On the PCSC layer, I am not sure. Maybe [`SCardForgetReader`](https://docs.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardforgetreadera) is it? This crate currently doesn't expose it, because it is not portable. But you can try it anyway with a wrapper like this:

```rust
#[cfg_attr(target_os = "windows", link(name = "winscard"))]
extern "system" {
    #[cfg_attr(target_os = "windows", link_name = "SCardForgetReaderA")]
    pub fn SCardForgetReader(
        hContext: pcsc_sys::SCARDCONTEXT,
        szReaderName: *const c_char,
    ) -> LONG;
}
```
