### ISSUE TITLE
Out of bounds range index access

### ISSUE THREAD

**Issue by n-eq** [bluetech/pcsc-rust#44]
Hello,

We're using the library to deal with card readers and on Windows we noticed random panics due to out of bounds ranges. The end index is however not always the same:

<img width="437" alt="image" src="https://github.com/bluetech/pcsc-rust/assets/16545838/e47fcd1f-7881-4c94-bf87-cff2daa90371">

When looking at the stacktrace the culprit seems to be `list_readers`.

<img width="572" alt="Screenshot 2023-10-03 at 10 24 07" src="https://github.com/bluetech/pcsc-rust/assets/16545838/fe0f08ad-4fb5-46e3-bba7-7338403c4af7">

And looking at the code, I guess this is the line that causes the problem: https://github.com/bluetech/pcsc-rust/blob/3246972a297f02c99f45fc4599d7c4bdba3cc250/pcsc/src/lib.rs#L809

The calling code is simple as this:

```rs
let ctx = pcsc::Context::establish(Scope::User)?;
let devices = ctx.list_readers_owned()?;
for d in devices {
    /* ... */
}
```

Do you have an idea what might be the issue here? Side question: is it a design choice to _unsafely_ (since it's panic-prone) access slices? If not, would you be interested in implementing other alternatives, using [get](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get) for example?

Thanks!
Nabil

**Comment by bluetech** [comment]
After some thinking I think I see how this can happen. The code of `list_readers_owned`:

```rs
    pub fn list_readers_owned(&self) -> Result<Vec<CString>, Error> {
        let mut buffer = vec![0u8; self.list_readers_len()?];
        Ok(self.list_readers(&mut buffer)?.map(ToOwned::to_owned).collect())
    }
```

Scenario:

- `list_readers_len()` returns 0 (=> `SCardListReaders` returned `SCARD_E_NO_READERS_AVAILABLE`).
- Now `buffer` is a zero-sized vec.
- `buffer.as_mut_ptr() ` must be `NULL` (I guess it's possible for a zero-sized vec?)
- Then the `SCardListReaders` in `list_readers`, having been given a `null` buffer, returns the expected length instead of the actual length.
- Panic!

I'll prepare a fix, thanks for the report.
