### ISSUE TITLE
`Vendored` feature for static linking

### ISSUE THREAD

**Issue by kpcyrd** [bluetech/pcsc-rust#59]
Hello!

I'm curious about having a `vendored` feature on the `pcsc-sys` crate that would use a vendored copy of libpcsc instead of using pkg-config.

There's examples for this in other crates:

- [openssl-sys](https://github.com/sfackler/rust-openssl/blob/538a5cb737e8d83085553cac01643820dc7ff205/openssl-sys/build/main.rs#L47-L57)
- [lzma-sys](https://github.com/alexcrichton/xz2-rs/blob/1a82c40d6d80171b7df328aea43b7054acd10c44/lzma-sys/build.rs#L15-L23)

In case of openssl, the vendored source code is placed in `openssl-src`, which is an optional dependency enabled through the `vendored` feature.

Thanks!

**Comment by bluetech** [comment]
Statically linking libpcsclite is not recommended because the libpcsclite <-> pcscd IPC interface [is not stable](https://github.com/LudovicRousseau/PCSC/blob/b165b151901c1c513f10814add21fb75628a7e5f/src/winscard_svc.c#L400-L411) and regularly changes (last change to the protocol version was 5 months ago).

**Comment by kpcyrd** [comment]
I see, thanks!
